package com.dynamoflightservice.app.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

@DynamoDbBean
public class Flight {
	
	
	private String flightId;

	private String flightName;

	private int flightseatCapacity;
	private String airlineName;
	
	@DynamoDBAutoGeneratedKey
	@DynamoDbPartitionKey
	@DynamoDBHashKey(attributeName="flightId")
	public String getFlightId() {
		return flightId;
	}
	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}
	
	@DynamoDbSortKey
	public String getFlightName() {
		return flightName;
	}
	public void setFlightName(String flightName) {
		this.flightName = flightName;
	}
	@DynamoDbAttribute(value = "flightseatCapacity")
	public int getFlightseatCapacity() {
		return flightseatCapacity;
	}
	public void setFlightseatCapacity(int flightseatCapacity) {
		this.flightseatCapacity = flightseatCapacity;
	}
	@DynamoDbAttribute(value = "airlineName")
	public String getAirlineName() {
		return airlineName;
	}
	public void setAirlineName(String airlineName) {
		this.airlineName = airlineName;
	}
	@Override
	public String toString() {
		return "Flight [flightId=" + flightId + ", flightName=" + flightName + ", flightseatCapacity="
				+ flightseatCapacity + ", airlineName=" + airlineName + "]";
	}
	public Flight(String flightId, String flightName, int flightseatCapacity, String airlineName) {
		super();
		this.flightId = flightId;
		this.flightName = flightName;
		this.flightseatCapacity = flightseatCapacity;
		this.airlineName = airlineName;
	}

	public Flight() {}
	
}
